[package]
name = "cloudsync"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
firestore = "0.11"
async-trait = "0.1.57"


[dependencies.gcloud-sdk]
version = "0.19"
features = ["google-firestore-v1"]